spring:
  application:
    name: product-service

  liquibase:
    change-log: classpath:database/liquibase-changelog.yml
    url: \${DB_URL:jdbc:postgresql://localhost:5432/product-service}
    user: \${DB_USERNAME:postgres}
    password: \${DB_PASSWORD:postgres}
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: \${DB_URL:jdbc:postgresql://localhost:5432/product-service}
    username: \${DB_USERNAME:postgres}
    password: \${DB_PASSWORD:postgres}

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    defer-datasource-initialization: false

app:
  version: ${version}
  name: \${spring.application.name}
  description: ${description}

server:
  port: 8090